# Electricity Generation from api.electricitymap.org
---

SECTION 1 
collect data on carbon intensity, zones within SW , and power breakdown from the electricitymap api

In [43]:
# Dependencies and Setup

import pandas as pd
import requests

In [44]:

# zones for electrical utilities in US
zones = ["US-SW-PNM", "US-SW-EPE", "US-SW-WALC", "US-NW-PACE", "US-NW-PSCO", "US-CENT-SWPP", "US-TEX-ERCO", "US-MIDW-AECI","US-SW-AZPS","US-SW-AZPS",
         "US-NW-WACM", "US-SW-SRP", "US-SW-TEPC", "US-CENT-SPA", "US-CAL-IID", "US-CAL-CISO", "US-CAL-BANC","US-CAL-BANC", "US-CAL-TIDC", 
          "US-CAR-CPLE", "US-CAR-CPLW", "US-CAR-DUK", "US-CAR-SC", "US-CAR-SCEG", "US-CAR-YAD", "US-FLA-FMPP", "US-FLA-FPC" , "US-FLA-FPL",
          "US-FLA-GVL" , "US-FLA-HST", "US-FLA-JEA", "US-FLA-SEC", "US-FLA-TAL", "US-FLA-TEC", "US-MIDW-AECI" , "US-MIDW-LGEE", "US-MIDW-MISO",
          "US-NE-ISNE", "US-NW-BPAT", "US-NW-CHPD", "US-NW-DOPD", "US-NW-GCPD", "US-NW-GRID",  "US-NW-IPCO" , "US-NW-NWMT", "US-NW-NEVP", 
           "US-NW-PACW",  "US-NW-PGE", "US-NW-PSEI", "US-NW-SCL", "US-NW-TPWR", "US-NW-WAUW", "US-NY-NYIS", "US-SE-SEPA", "US-SE-SOCO" , 
           "US-TEN-TVA"]

In [45]:

# get carbon intensity history for the US utilities
urls = []
for index, url in enumerate(zones):
    url = f'https://api.electricitymap.org/v3/carbon-intensity/history?zone={zones[index]}'
    urls.append(url)

responses_dict = {}
for idx, url in enumerate(urls):
    response = requests.get(url)
    responses_dict[f"response_{idx+1}"] = response.json()

# Specify the file path where you want to save the JSON file
import json

file_path = "C_intensity_history_data.json"

# Write the dictionary to a JSON file
with open(file_path, 'w') as json_file:
    json.dump(responses_dict, json_file, indent=4)

print("Dictionary successfully exported to JSON file.")

df_carbon_intensity_history = pd.read_json(file_path)

Dictionary successfully exported to JSON file.

In [46]:
#request power breakdown
pburls = []
for index, url in enumerate(zones):
    pburl = f'https://api.electricitymap.org/v3/power-breakdown/history?zone={zones[index]}'
    pburls.append(pburl)

power_breakdown_responses_dict = {}
for idx, pburl in enumerate(pburls):
    response = requests.get(pburl)
    power_breakdown_responses_dict[f"response_{idx+1}"] = response.json()

# Specify the file path where you want to save the JSON file

file_path = "power_breakdown_history_data.json"

# Write the dictionary to a JSON file
with open(file_path, 'w') as json_file:
    json.dump(power_breakdown_responses_dict, json_file, indent=4)

df_power_breakdown_history = pd.read_json(file_path)

SECTION 2     
PowerBreakdown data transformation

In [47]:
# pull data from power breakdown json in dataframe
region = df_power_breakdown_history['response_1']['history'][0]['zone']
datetime = df_power_breakdown_history['response_1']['history'][0]['datetime']
nuclear = df_power_breakdown_history['response_1']['history'][0]["powerConsumptionBreakdown"]['nuclear']
geothermal = df_power_breakdown_history['response_1']['history'][0]["powerConsumptionBreakdown"]['geothermal']
biomass = df_power_breakdown_history['response_1']['history'][0]["powerConsumptionBreakdown"]['biomass']
coal = df_power_breakdown_history['response_1']['history'][0]["powerConsumptionBreakdown"]['coal']
wind = df_power_breakdown_history['response_1']['history'][0]["powerConsumptionBreakdown"]['wind']
solar = df_power_breakdown_history['response_1']['history'][0]["powerConsumptionBreakdown"]['solar']
hydro = df_power_breakdown_history['response_1']['history'][0]["powerConsumptionBreakdown"]['hydro']
gas = df_power_breakdown_history['response_1']['history'][0]["powerConsumptionBreakdown"]['gas']
oil = df_power_breakdown_history['response_1']['history'][0]["powerConsumptionBreakdown"]['oil']
unknown = df_power_breakdown_history['response_1']['history'][0]["powerConsumptionBreakdown"]['unknown']
hydro_discharge = df_power_breakdown_history['response_1']['history'][0]["powerConsumptionBreakdown"]['hydro discharge']
battery_discharge = df_power_breakdown_history['response_1']['history'][0]["powerConsumptionBreakdown"]['battery discharge']
renewable_percentage = df_power_breakdown_history['response_1']['history'][0]["renewablePercentage"]
total_consumption = df_power_breakdown_history['response_1']['history'][0]["powerConsumptionTotal"]
estimated = df_power_breakdown_history['response_1']['history'][0]["isEstimated"]

# create a dictionary with first values for this zone
us_pnm1 = {'region':region,'datetime':datetime,'nuclear':nuclear,'geothermal':geothermal,'biomass':biomass, 'coal':coal, 'wind':wind, 'solar':solar, 
           'hydro':hydro, 'gas':gas, 'oil':oil, 'unknown':unknown, 'hydro-discharge':hydro_discharge, 
           'battery_discharge':battery_discharge, 'renewable_percentage':renewable_percentage, 'total_consumption':total_consumption, 
           'estimated':estimated}

# Create a dataFrame with the first values
df_US = pd.DataFrame.from_dict(us_pnm1,orient='index')

In [48]:
# Data wrangling from the response to create a legible dataFrame
# outer for loop for regions/responses
for reg in range(len(zones)):
    #for each zone
    response = f"response_{reg+1}"
   
# pull data from json for each time in this file for this region and add to the existing dataframe
    for i in range(24):
        # 24 is for the 24 hours of data for each zone
        region = df_power_breakdown_history[f"{response}"]['history'][i]['zone']
        datetime = df_power_breakdown_history[f"{response}"]['history'][i]['datetime']
        nuclear = df_power_breakdown_history[f"{response}"]['history'][i]["powerConsumptionBreakdown"]['nuclear']
        geothermal = df_power_breakdown_history[f"{response}"]['history'][i]["powerConsumptionBreakdown"]['geothermal']
        biomass = df_power_breakdown_history[f"{response}"]['history'][i]["powerConsumptionBreakdown"]['biomass']
        coal = df_power_breakdown_history[f"{response}"]['history'][i]["powerConsumptionBreakdown"]['coal']
        wind = df_power_breakdown_history[f"{response}"]['history'][i]["powerConsumptionBreakdown"]['wind']
        solar = df_power_breakdown_history[f"{response}"]['history'][i]["powerConsumptionBreakdown"]['solar']
        hydro = df_power_breakdown_history[f"{response}"]['history'][i]["powerConsumptionBreakdown"]['hydro']
        gas = df_power_breakdown_history[f"{response}"]['history'][i]["powerConsumptionBreakdown"]['gas']
        oil = df_power_breakdown_history[f"{response}"]['history'][i]["powerConsumptionBreakdown"]['oil']
        unknown = df_power_breakdown_history[f"{response}"]['history'][i]["powerConsumptionBreakdown"]['unknown']
        hydro_discharge = df_power_breakdown_history[f"{response}"]['history'][i]["powerConsumptionBreakdown"]['hydro discharge']
        battery_discharge = df_power_breakdown_history[f"{response}"]['history'][i]["powerConsumptionBreakdown"]['battery discharge']
        renewable_percentage = df_power_breakdown_history[f"{response}"]['history'][i]["renewablePercentage"]
        total_consumption = df_power_breakdown_history[f"{response}"]['history'][i]["powerConsumptionTotal"]
        estimated = df_power_breakdown_history[f"{response}"]['history'][i]["isEstimated"]

        # this 24 is also for the 23 hours of data for each zone
        df_US[24*reg+i]= {'region':region, 'datetime':datetime,'nuclear':nuclear,'geothermal':geothermal,'biomass':biomass, 'coal':coal, 'wind':wind, 'solar':solar, 
           'hydro':hydro, 'gas':gas, 'oil':oil, 'unknown':unknown, 'hydro-discharge':hydro_discharge, 
           'battery_discharge':battery_discharge, 'renewable_percentage':renewable_percentage, 'total_consumption':total_consumption, 
           'estimated':estimated}
#set up the times as rows and measurements as columns
df_US_new = df_US.transpose()

# check data types
df_US_new.describe()

C:\Users\mrkol\AppData\Local\Temp\ipykernel_11696\3249227210.py:29: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_US[24*reg+i]= {'region':region, 'datetime':datetime,'nuclear':nuclear,'geothermal':geothermal,'biomass':biomass, 'coal':coal, 'wind':wind, 'solar':solar,

,region,datetime,nuclear,geothermal,biomass,coal,wind,solar,hydro,gas,oil,unknown,hydro-discharge,battery_discharge,renewable_percentage,total_consumption,estimated
count,1344,1344,1342,1342,1342,1342,1342,1342,1342,1342,1342,1342,1342,1342,1344,1342,1344
unique,53,24,283,23,58,533,319,401,544,891,34,279,2,35,86,1095,2
top,US-CAL-BANC,2024-07-20T18:00:00.000Z,0,0,0,0,0,0,0,0,0,0,0,0,0,144,False
freq,48,56,821,1318,1213,612,804,705,345,197,1251,538,1341,1299,203,8,682

In [49]:
# fill NA values with zeroes for energy values
df_US_new = df_US_new.fillna({'nuclear': 0,'geothermal': 0,'biomass': 0, 'coal': 0, 'wind': 0, 'solar': 0, 
           'hydro': 0, 'gas': 0, 'oil': 0, 'unknown': 0, 'hydro-discharge':0, 
           'battery_discharge':0})
df_US_new.describe()

,nuclear,geothermal,biomass,coal,wind,solar,hydro,gas,oil,unknown,hydro-discharge,battery_discharge
count,1344.000000,1344.000000,1344.000000,1344.00000,1344.000000,1344.000000,1344.000000,1344.000000,1344.000000,1344.000000,1344.000000,1344.000000
mean,1152.064732,12.442708,19.779762,1504.11756,322.386161,481.515625,617.276042,3791.421131,1.483631,91.093750,0.216518,19.354911
std,2502.034100,92.641325,100.480405,3668.33974,1318.138751,1946.846725,2178.329835,7507.070200,7.255862,204.848821,7.937676,298.074436
min,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,286.500000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,129.00000,0.000000,0.000000,79.000000,1024.500000,0.000000,9.000000,0.000000,0.000000
75%,405.500000,0.000000,0.000000,1238.50000,60.250000,185.000000,640.000000,2463.500000,0.000000,90.000000,0.000000,0.000000
max,13695.000000,767.000000,608.000000,27569.00000,14841.000000,17421.000000,65867.000000,45611.000000,84.000000,2053.000000,291.000000,6703.000000

In [50]:
# convert measured Energy values to integers in Giga Watts
convert_dict = {'hydro': int}
#convert_dict = {'nuclear': int, 'geothermal': int, 'biomass': int, 'coal': int, 'wind': int, 'solar': int, 'hydro': int, 'gas': int, 'oil': int, 
             #   'hydro-discharge': int, 'battery_discharge': int, 'renewable_percentage': int, 'total_consumption': int
               # }
 # note - the unknown column only has values rarely - converting null values to integer doesn't work so this is left as an object
df_US_new = df_US_new.astype(convert_dict)

#check that data types are changed to int
df_US_new.dtypes

region                  object
datetime                object
nuclear                  int64
geothermal               int64
biomass                  int64
coal                     int64
wind                     int64
solar                    int64
hydro                    int32
gas                      int64
oil                      int64
unknown                  int64
hydro-discharge          int64
battery_discharge        int64
renewable_percentage    object
total_consumption       object
estimated               object
dtype: object

In [51]:
# Date Time work

# import datetime dependencies

from datetime import datetime

# set up lists to hold parsed data and DateTime as a datetime datetype
dates=[]
times = []
DateTime =[]

# convert date time strings
for i in range(len(df_US_new['datetime'])):

    # Parse the timestamp string to a datetime object
    dt_obj = datetime.strptime(df_US_new.iloc[i,1], '%Y-%m-%dT%H:%M:%S.%fZ')

    date = dt_obj.strftime('%Y-%m-%d')
    time = dt_obj.strftime('%H:%M:%S')

#add the new times and dates to lists

    dates.append(date)
    times.append(time)
    DateTime.append(dt_obj)

# add the times and dates to new columns in the data frame
df_US_new['UTC time'] = times
df_US_new['UTC date'] = dates
df_US_new['UTC DateTime'] = DateTime

In [52]:
#set the UTC DateTime as the index
df_US_new_reindex = df_US_new.set_index('UTC DateTime', inplace=True)

#drop the datetime column that contains a string
df_US_newer = df_US_new.drop('datetime', axis=1)
df_US_newer.head()

,region,nuclear,geothermal,biomass,coal,wind,solar,hydro,gas,oil,unknown,hydro-discharge,battery_discharge,renewable_percentage,total_consumption,estimated,UTC time,UTC date
UTC DateTime,,,,,,,,,,,,,,,,,,
2024-07-20 18:00:00,US-SW-PNM,0,0,0,236,4,934,18,513,0,0,0,0,56,1705,False,18:00:00,2024-07-20
2024-07-20 19:00:00,US-SW-PNM,0,0,0,337,24,820,18,587,0,0,0,0,48,1786,False,19:00:00,2024-07-20
2024-07-20 20:00:00,US-SW-PNM,0,0,0,355,111,788,18,598,0,0,0,0,49,1870,False,20:00:00,2024-07-20
2024-07-20 21:00:00,US-SW-PNM,0,0,0,401,341,673,18,692,0,0,0,0,49,2125,False,21:00:00,2024-07-20
2024-07-20 22:00:00,US-SW-PNM,0,0,0,468,832,727,18,718,0,11,0,0,57,2774,False,22:00:00,2024-07-20

Section 3
Transform carbon intensity data

In [53]:
# pull data from C intensity json in dataframe
region = df_carbon_intensity_history['response_1']['history'][0]['zone']
datetime = df_carbon_intensity_history['response_1']['history'][0]['datetime']
carbon_Intensity = df_carbon_intensity_history['response_1']['history'][0]["carbonIntensity"]
estimated = df_carbon_intensity_history['response_1']['history'][0]["isEstimated"]

# create a dictionary with first values for this zone
us_pnm1C = {'region':region,'datetime':datetime,'Carbon_Intensity':carbon_Intensity, 'estimated':estimated}

# Create a dataFrame with the first values
df_US_C = pd.DataFrame.from_dict(us_pnm1C,orient='index')

In [54]:
# Data wrangling from the response to create a legible dataFrame for carbon intensity history

# outer for loop for regions/responses
for reg in range(len(zones)):
    response = f"response_{reg+1}"
    
# pull data from json for each time in this file for this region and add to the existing dataframe
    for i in range(24):
        # 24 is for the 24 hours of data for each zone
        region = df_carbon_intensity_history[f"{response}"]['history'][i]['zone']
        datetime = df_carbon_intensity_history[f"{response}"]['history'][i]['datetime']
        carbon_Intensity = df_carbon_intensity_history['response_1']['history'][i]["carbonIntensity"]
        estimated = df_carbon_intensity_history['response_1']['history'][i]["isEstimated"]
        
        # this 24 is also for the 24 hours of data in each zone
        df_US_C[24*reg+i]= {'region':region, 'datetime':datetime,'Carbon_Intensity':carbon_Intensity, 'estimated':estimated}

# make the datetime the rows and carbon_intensity a column
df_US_C_new = df_US_C.transpose()

# check data types
df_US_C_new.dtypes

C:\Users\mrkol\AppData\Local\Temp\ipykernel_11696\3332989139.py:16: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_US_C[24*reg+i]= {'region':region, 'datetime':datetime,'Carbon_Intensity':carbon_Intensity, 'estimated':estimated}

region              object
datetime            object
Carbon_Intensity    object
estimated           object
dtype: object

In [55]:
# convert carbon intensity measurement to an integer in g CO2e/kWh
convert_dict_C= {'Carbon_Intensity': int}
 
df_US_C_new = df_US_C_new.astype(convert_dict_C)

#check that the datatype has been changed
df_US_C_new.dtypes

region              object
datetime            object
Carbon_Intensity     int32
estimated           object
dtype: object

In [56]:
# add the times and dates to new columns in the data frame   -    This assumes the data for carbon intensity is pulled at the same time as power breakdown
df_US_C_new['UTC time'] = times
df_US_C_new['UTC date'] = dates
df_US_C_new['UTC DateTime'] = DateTime

#set the UTC DateTime as the index
df_US_C_new_reindex = df_US_C_new.set_index('UTC DateTime', inplace=True)
#drop the datetime column that contains a string
df_US_C_newer = df_US_C_new.drop('datetime', axis=1)

Section 4
Merge dataframes

In [57]:
df_power_and_carbon= pd.merge(df_US_newer, df_US_C_newer,on=['UTC DateTime','region','UTC time','UTC date'])



df_power_and_carbon.rename(columns={'Carbon_Intensity':'Carbon_Intensity(gCO2eq/kWh)','total_consumption':'total_consumption(GW)', 'nuclear':'nuclear(GW)', 
                                    'geothermal':'geothermal(GW)', 'biomass':'biomass(GW)', 'coal':'coal(GW)', 'wind':'wind(GW)', 'solar':'solar(GW)', 
                                    'hydro':'hydro(GW)','gas':'gas(GW)', 'region_x': 'region', 'estimated_x': 'breakdown estimated?','estimated_y':'intensity estimated?'}, inplace=True)




df_power_and_carbon.head()

,region,nuclear(GW),geothermal(GW),biomass(GW),coal(GW),wind(GW),solar(GW),hydro(GW),gas(GW),oil,unknown,hydro-discharge,battery_discharge,renewable_percentage,total_consumption(GW),breakdown estimated?,UTC time,UTC date,Carbon_Intensity(gCO2eq/kWh),intensity estimated?
UTC DateTime,,,,,,,,,,,,,,,,,,,,
2024-07-20 18:00:00,US-SW-PNM,0,0,0,236,4,934,18,513,0,0,0,0,56,1705,False,18:00:00,2024-07-20,349,False
2024-07-20 19:00:00,US-SW-PNM,0,0,0,337,24,820,18,587,0,0,0,0,48,1786,False,19:00:00,2024-07-20,424,False
2024-07-20 20:00:00,US-SW-PNM,0,0,0,355,111,788,18,598,0,0,0,0,49,1870,False,20:00:00,2024-07-20,420,False
2024-07-20 21:00:00,US-SW-PNM,0,0,0,401,341,673,18,692,0,0,0,0,49,2125,False,21:00:00,2024-07-20,420,False
2024-07-20 22:00:00,US-SW-PNM,0,0,0,468,832,727,18,718,0,11,0,0,57,2774,False,22:00:00,2024-07-20,362,False

In [58]:
# import previous cleaned file into a pandas dataframe
df_us_energy = pd.read_csv('data/runningUSenergy_data.csv')
df_us_energy_reindex=df_us_energy.set_index("UTC DateTime")
df_us_energy_reindex.describe()

,nuclear(GW),geothermal(GW),biomass(GW),coal(GW),wind(GW),solar(GW),hydro(GW),gas(GW),oil,unknown,hydro-discharge,battery_discharge,renewable_percentage,total_consumption(GW),Carbon_Intensity(gCO2eq/kWh)
count,11045.000000,11045.000000,11045.000000,11045.000000,11045.000000,11045.000000,11045.000000,11045.000000,11045.000000,11045.000000,11045.000000,11045.000000,10985.000000,11004.000000,11045.000000
mean,1230.553825,15.327660,24.130376,1754.094794,652.917700,527.294522,657.251607,4198.320054,7.570665,99.411408,0.793210,20.216297,32.526354,9222.169302,396.049615
std,2557.664321,106.753071,111.143936,4647.501862,2212.528265,2059.930206,1399.097061,8189.850533,57.892709,208.129848,16.300759,290.932839,34.311529,16890.086782,168.970453
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,113.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,237.000000,0.000000,0.000000,0.000000,0.000000,5.000000,915.750000,257.000000
50%,0.000000,0.000000,0.000000,38.000000,0.000000,0.000000,74.000000,997.000000,0.000000,9.000000,0.000000,0.000000,19.000000,2402.000000,373.000000
75%,921.000000,0.000000,0.000000,1376.000000,215.000000,190.000000,716.000000,3381.000000,0.000000,95.000000,0.000000,0.000000,50.000000,9348.250000,544.000000
max,13803.000000,812.000000,657.000000,49357.000000,21642.000000,19768.000000,11538.000000,54713.000000,2054.000000,1864.000000,557.000000,7075.000000,100.000000,117668.000000,801.000000

In [59]:
df_us_energy_reindex.drop_duplicates(inplace=True)
df_us_energy_reindex.describe()

,nuclear(GW),geothermal(GW),biomass(GW),coal(GW),wind(GW),solar(GW),hydro(GW),gas(GW),oil,unknown,hydro-discharge,battery_discharge,renewable_percentage,total_consumption(GW),Carbon_Intensity(gCO2eq/kWh)
count,11045.000000,11045.000000,11045.000000,11045.000000,11045.000000,11045.000000,11045.000000,11045.000000,11045.000000,11045.000000,11045.000000,11045.000000,10985.000000,11004.000000,11045.000000
mean,1230.553825,15.327660,24.130376,1754.094794,652.917700,527.294522,657.251607,4198.320054,7.570665,99.411408,0.793210,20.216297,32.526354,9222.169302,396.049615
std,2557.664321,106.753071,111.143936,4647.501862,2212.528265,2059.930206,1399.097061,8189.850533,57.892709,208.129848,16.300759,290.932839,34.311529,16890.086782,168.970453
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,113.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,237.000000,0.000000,0.000000,0.000000,0.000000,5.000000,915.750000,257.000000
50%,0.000000,0.000000,0.000000,38.000000,0.000000,0.000000,74.000000,997.000000,0.000000,9.000000,0.000000,0.000000,19.000000,2402.000000,373.000000
75%,921.000000,0.000000,0.000000,1376.000000,215.000000,190.000000,716.000000,3381.000000,0.000000,95.000000,0.000000,0.000000,50.000000,9348.250000,544.000000
max,13803.000000,812.000000,657.000000,49357.000000,21642.000000,19768.000000,11538.000000,54713.000000,2054.000000,1864.000000,557.000000,7075.000000,100.000000,117668.000000,801.000000

In [60]:
# concatentate current data with existing file
df_both = pd.concat([df_us_energy_reindex,df_power_and_carbon])

# drop duplicate rows
df_both.drop_duplicates(inplace=True)
df_both.describe()

,nuclear(GW),geothermal(GW),biomass(GW),coal(GW),wind(GW),solar(GW),hydro(GW),gas(GW),oil,unknown,hydro-discharge,battery_discharge,Carbon_Intensity(gCO2eq/kWh)
count,12317.000000,12317.00000,12317.000000,12317.000000,12317.000000,12317.000000,12317.000000,12317.000000,12317.000000,12317.000000,12317.000000,12317.000000,12317.000000
mean,1229.133799,15.10246,23.796704,1731.420476,620.345052,524.483884,654.829260,4170.268897,6.950719,98.859544,0.734919,20.240481,407.103191
std,2557.459988,105.61519,110.347903,4564.582186,2141.936954,2053.627946,1506.961363,8140.190461,54.904280,208.223466,15.657951,292.551278,170.267252
min,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,113.000000
25%,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,238.000000,0.000000,0.000000,0.000000,0.000000,266.000000
50%,0.000000,0.00000,0.000000,38.000000,0.000000,0.000000,75.000000,991.000000,0.000000,9.000000,0.000000,0.000000,382.000000
75%,736.000000,0.00000,0.000000,1368.000000,195.000000,190.000000,712.000000,3314.000000,0.000000,95.000000,0.000000,0.000000,556.000000
max,13803.000000,812.00000,657.000000,49357.000000,21642.000000,19768.000000,65867.000000,54713.000000,2054.000000,2053.000000,557.000000,7075.000000,801.000000

In [61]:
#df_both.to_csv(f'data/{dates[0]}USenergy_data2.csv')
df_both.to_csv(f'data/runningUSenergy_data.csv')

In [62]:
df_both_cleaned = df_both.loc[df_both['breakdown estimated?']==False,:]
df_both_cleaned.describe()

,nuclear(GW),geothermal(GW),biomass(GW),coal(GW),wind(GW),solar(GW),hydro(GW),gas(GW),oil,unknown,hydro-discharge,battery_discharge,Carbon_Intensity(gCO2eq/kWh)
count,4376.000000,4376.000000,4376.000000,4376.000000,4376.000000,4376.000000,4376.000000,4376.000000,4376.000000,4376.000000,4376.000000,4376.000000,4376.000000
mean,1347.987431,40.813528,61.816956,1887.266910,998.741316,700.736517,1034.737203,5243.010512,14.284735,116.933729,0.000457,55.288620,390.085923
std,2326.880108,170.624401,170.947332,4604.869648,2718.630504,2622.954750,1929.009755,8370.025906,83.204524,231.963593,0.021376,484.953484,141.891529
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,113.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,11.000000,270.000000,0.000000,0.000000,0.000000,0.000000,283.000000
50%,0.000000,0.000000,0.000000,32.000000,28.000000,1.000000,216.000000,1366.000000,0.000000,13.000000,0.000000,0.000000,375.000000
75%,2214.000000,0.000000,0.000000,1285.000000,419.250000,224.000000,1294.250000,7948.000000,0.000000,126.250000,0.000000,0.000000,460.000000
max,13287.000000,812.000000,657.000000,48997.000000,21642.000000,19768.000000,65867.000000,54713.000000,2054.000000,2053.000000,1.000000,7075.000000,801.000000

In [63]:
df_both_cleaned.to_csv(f'data/runningUSenergy_data_filtered.csv')